name: Build and Deploy to gh-pages

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-build
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download content from content repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_KEY }}
          repository: bre97-web/blog-content
          sparse-checkout: |
            content
          path: ./temp
      - name: Build website
        run: cp -r ./temp/content/* ./src/content && npm install && npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
