name: Deploy to gh-pages

on:
    workflow_dispatch:
    repository_dispatch:
        types:
          - trigger-build
    push:
        branches:
          - main

jobs:              
    deploy-to-github:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Download content from repository
            uses: actions/checkout@v4
            with:
                token: ${{ secrets.DEPLOY_KEY }}
                repository: bre97-web/blog-content
                sparse-checkout: |
                    blogs
                path: ./temp

          - name: Copy remote blogs folder to src/content/blogs/*
            run: |
                echo "Display files in the temp folder." && 
                tree ./temp && 

                echo "Clear the default files in the src/content/blogs folder."
                rm -rf ./src/content/blogs && 
                mkdir -p ./src/content/blogs && 
                cp -r ./temp/blogs/* ./src/content/blogs && 

                echo "Display files in the src/content/blogs folder." && 
                tree ./src/content

          - name: Run build:gh
            run:  npm install && npm run build:gh

          - name: Deploy to gh-pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
